### ISSUE TITLE
NSP files are visible but I can't install any of them

### ISSUE THREAD

**Issue by ULTRNS** [ajmandourah/tinshop-ng#3]
Hello,

I tried adding Tinshop using Portainer, the container is installed and seems to be running fine. I added reverse proxy using the one provided by Synology.

![2024-10-18 14_41_44-Batnas2 - Synology NAS — Mozilla Firefox](https://github.com/user-attachments/assets/ad435d70-5e9f-42a2-b9fc-00b95351c319)

I can access my shop using Tinfoil, with those parameters : 

Protocol : Https
Host : address I put in the reverse proxy
Port : 443
Path /

I see the NSP test files I added in the game directory but when I try to install it using the File Browser it says that it failed to load the NSP.

When I try to use the "New Games" tile it will open the Installing window but it stays at 0 mbps and after a few seconds the window closes, in the queue tab I see the nsp file with the Complete status but it never installs.

Here is the config.yaml file content :

![2024-10-18 14_45_25-P__Tinshop_config_config yaml - Notepad++](https://github.com/user-attachments/assets/c4207811-7693-4236-ad2d-47c5c92c3739)

And the logs from the container : 

![2024-10-18 14_50_17-Portainer _ local — Mozilla Firefox](https://github.com/user-attachments/assets/640c4b89-f0ab-49a7-ab9d-9436a0da77f8)

**Comment by ajmandourah** [comment]
Thanks for submitting the issue.
Is the last 3 log messages related to you trying to download/install the nsp?
If so strangely enough it seems that an agent header is appended there and this should not be the case as tinfoil itself does not send any agent header.

If not its another issue. Try first setting no security config to true and see if it's working.

**Comment by ULTRNS** [comment]
The Agent Header was appearing only when browsing the shop and trying to install the nsp file there. 

Yes, I'm using the latest tag in the docker compose file : ghcr.io/ajmandourah/tinshop-ng:latest

I set the no security to true and now it's working fine, thanks for your help

**Comment by ajmandourah** [comment]
> The Agent Header was appearing only when browsing the shop and trying to install the nsp file there. 
> 
> Yes, I'm using the latest tag in the docker compose file : ghcr.io/ajmandourah/tinshop-ng:latest
> 
> I set the no security to true and now it's working fine, thanks for your help

For local instances it's OK but I would set it to false if I am using it remotely. 

One thing to check in synology reverse proxy setting. Make sure the custom headers option is empty. In general reverse proxies should not be setting an agent header as these should be passed by the original request.

**Comment by ULTRNS** [comment]
I doubled check the custom headers on the reverse proxy and I confirm that there is nothing set. 

I tried setting no security to false again and the problem comes back "Cannot load NSP file"

**Comment by ajmandourah** [comment]
Can you try pulling the testing tag container. i have removed the check for the agent headers. report if its working now

**Comment by ajmandourah** [comment]
Fixed in the latest release. Repull the latest image and test please.

**Comment by ULTRNS** [comment]
Hello,

I just repulled the image and set the no security to false and was able to download a NSP using Tinfoil.

Thank you very much for your help

**Comment by ajmandourah** [comment]
> Hello,
> 
> I just repulled the image and set the no security to false and was able to download a NSP using Tinfoil.
> 
> Thank you very much for your help

No worries. Glad it worked.

For future references and other devs: tinfoil sends their special headers to root mainly. Links for files and such are otherwise without any of their special headers. This is obvious as these links can be public links also.
I will need to send a customized header for verification to have some sort of protection against forged requests.
