### ISSUE TITLE
Number of games found changes, but still doesn't match actual number of files

### ISSUE THREAD

**Issue by bjstrange** [ajmandourah/tinshop-ng#4]
I have 194 files in the folder.

All are named correctly. I renamed all files to sequential numbers and then let tinshop rename them all as it saw fit. Tinshop logs shows 194 entries like

tinshop  | 2024-10-19T17:41:31.395673978Z 2024/10/19 17:41:31 Data parsed from  /games/base/0/3 Minutes to Midnight® [01009F70203E6000][v0].nsz

Start tinshop
tinshop  | 2024-10-19T17:41:01.629700033Z 2024/10/19 17:41:01 Added 110 games in your library
tinshop  | 2024-10-19T17:41:01.655121989Z 2024/10/19 17:41:01 Total of 110 files in your library (110 in titledb section)
tinshop  | 2024-10-19T17:41:01.655145555Z 2024/10/19 17:41:01 Total of 107 unique games in your library

Stop tinshop, start it again
tinshop  | 2024-10-19T17:41:31.401705917Z 2024/10/19 17:41:31 Added 82 games in your library
tinshop  | 2024-10-19T17:41:31.647330838Z 2024/10/19 17:41:31 Total of 82 files in your library (82 in titledb section)
tinshop  | 2024-10-19T17:41:31.647786779Z 2024/10/19 17:41:31 Total of 80 unique games in your library

Still 194 entries parsed.

This is with latest docker version as of this post.

**Comment by ajmandourah** [comment]
Thanks for opening the issue. 
just to be clear you renamed them keeping the extensions intact right? Tinshop-ng need to know the extention of the files before hand as it filters files other than xci nsp and nsz out. 

can you check out if the unrecognized files have weird extension? like capitalized one for example
can you filter out somehow which file got ignored? I am using tinfoil's titledb json and it can be it is not updated (but it should be)
and lastly if you can provide the log where it ignored these files

**Comment by ajmandourah** [comment]
Another thing to notice if your files includes dlc/updates these will be considered one game in tinfoil entries.

**Comment by bjstrange** [comment]
All files are normal extensions. The rename kept the extensions intact. All are nsp, nsz, or xci files. I did have a couple non-game files, I have removed them. There are 188 files in this folder. All are base files, no other dlcs or updates are here.
[files.log](https://github.com/user-attachments/files/17447686/files.log)
[run1.log](https://github.com/user-attachments/files/17447687/run1.log)
[run2.log](https://github.com/user-attachments/files/17447688/run2.log)

I'm not sure which files are getting excluded. The filecount reported at the end of the log is the number of files available in tinfoil. That number keeps changing when nothing else on the filesystem has.

**Comment by ajmandourah** [comment]
> All files are normal extensions. The rename kept the extensions intact. All are nsp, nsz, or xci files. I did have a couple non-game files, I have removed them. There are 188 files in this folder. All are base files, no other dlcs or updates are here.
> [files.log](https://github.com/user-attachments/files/17447686/files.log)
> [run1.log](https://github.com/user-attachments/files/17447687/run1.log)
> [run2.log](https://github.com/user-attachments/files/17447688/run2.log)
> 
> I'm not sure which files are getting excluded. The filecount reported at the end of the log is the number of files available in tinfoil. That number keeps changing when nothing else on the filesystem has.

Thanks for providing the logs
This sounds like a race condition. I will look into it.

**Comment by ajmandourah** [comment]
Hey . can you try pulling this image and test it out. 
ghcr.io/ajmandourah/tinshop-ng:mutex

**Comment by bjstrange** [comment]
No change.

tinshop  | 2024-10-20T23:18:04.920348704Z 2024/10/20 23:18:04 Add new games...
tinshop  | 2024-10-20T23:18:04.921155932Z 2024/10/20 23:18:04 Added 82 games in your library
tinshop  | 2024-10-20T23:18:04.955689521Z 2024/10/20 23:18:04 Total of 82 files in your library (82 in titledb section)
tinshop  | 2024-10-20T23:18:04.955719724Z 2024/10/20 23:18:04 Total of 80 unique games in your library

tinshop  | 2024-10-20T23:19:30.176069250Z 2024/10/20 23:19:30 Add new games...
tinshop  | 2024-10-20T23:19:30.176877450Z 2024/10/20 23:19:30 Added 88 games in your library
tinshop  | 2024-10-20T23:19:30.199814115Z 2024/10/20 23:19:30 Total of 88 files in your library (88 in titledb section)
tinshop  | 2024-10-20T23:19:30.199881477Z 2024/10/20 23:19:30 Total of 86 unique games in your library

tinshop  | 2024-10-20T23:20:44.810330216Z 2024/10/20 23:20:44 Add new games...
tinshop  | 2024-10-20T23:20:44.811163983Z 2024/10/20 23:20:44 Added 85 games in your library
tinshop  | 2024-10-20T23:20:44.832294053Z 2024/10/20 23:20:44 Total of 85 files in your library (85 in titledb section)
tinshop  | 2024-10-20T23:20:44.832316098Z 2024/10/20 23:20:44 Total of 83 unique games in your library

**Comment by ajmandourah** [comment]
Tried to imitate your setup and indeed there was a race condition. it should work now. try repulling again the `mutex` tagged image. (delete the old mutex image)

**Comment by bjstrange** [comment]
Yep, that one works! Thanks!

**Comment by ajmandourah** [comment]
That's great. Merged now with latest.
