### ISSUE TITLE
Logs filled with security message

### ISSUE THREAD

**Issue by slimshizn** [ajmandourah/tinshop-ng#8]
As title says the logs are filling up.

`2024/11/12 19:30:24 [Security] User-Agent detected...`

Is this a misconfiguration?

**Comment by ajmandourah** [comment]
Hi an thanks for opening an issue.

This happens usually when you are trying to access Tinshop-ng from clients other than tinfoil itself ie. The browser.
Tinfoil usually does not include any user-agent header. So either you have accessed the shop through other means or someone is. Tinfoil to my testing does not do that as I mentioned.

**Comment by slimshizn** [comment]
Thank you for the update.
